# This workflow will do a clean install of node dependencies,
# build the source code, and lint the project.

name: Check and build wardrobe

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  # Default version of Node.js for jobs
  node-version: "20"

jobs:
  test-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
          cache: yarn
      - run: yarn install --immutable --immutable-cache --check-files
      - run: yarn run build

  lint-all:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: "main"

      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
          cache: yarn
      - run: yarn install --immutable --immutable-cache
      - run: yarn run lint
      - run: yarn run build

  deploy:
    runs-on: ubuntu-latest
    needs: [test-script, lint-all]
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
          cache: yarn
      - run: yarn install --immutable --immutable-cache
      - run: yarn build
      - uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: release
          FOLDER: KoLmafia
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: ${{ github.event.commits[0].message }}
